export const siteLogo = "images/logo.png";

export const headerTopMessage = "Content Goes Here If Any";
export const taxonomy = [
  {
    id: 1,
    dept: "Firearms",
    url: "firearms",
    typ: "Empty",
    subTyp_1: "Empty",
    subTyp_2: "Empty",
  },
  {
    id: 1,
    dept: "Firearms",
    typ: "Guns",
    url: "firearms-guns",
    subTyp_1: "Empty",
    subTyp_2: "Empty",
  },
  {
    id: 1,
    dept: "Firearms",
    typ: "Riffle",
    url: "firearms-riffle",
    subTyp_1: "Empty",
    subTyp_2: "Empty",
  },
  {
    id: 1,
    dept: "Firearms",
    typ: "Guns",
    subTyp_1: "Pistal",
    url: "firearms-guns-pistal",
    subTyp_2: "Empty",
  },
  {
    id: 1,
    dept: "Firearms",
    typ: "Guns",
    subTyp_1: "Short Gun",
    url: "firearms-guns-short-guns",
    subTyp_2: "Empty",
  },
  {
    id: 1,
    dept: "Firearms",
    typ: "Guns",
    subTyp_1: "Short Gun",
    subTyp_2: "Range Short Gun",
    url: "firearms-guns-range-short-gun",
  },
  {
    id: 1,
    dept: "Firearms",
    typ: "Riffle",
    subTyp_1: "AK47",
    url: "firearms-riffle-ak47",
    subTyp_2: "Empty",
  },
  {
    id: 2,
    dept: "Ammunition",
    url: "ammunition",
    typ: "Empty",
    subTyp_1: "Empty",
    subTyp_2: "Empty",
  },
  {
    id: 3,
    dept: "Archery",
    url: "archery",
    typ: "Empty",
    subTyp_1: "Empty",
    subTyp_2: "Empty",
  },
  {
    id: 4,
    dept: "Education",
    url: "education",
    typ: "Empty",
    subTyp_1: "Empty",
    subTyp_2: "Empty",
  },
  {
    id: 5,
    dept: "Accessories",
    url: "accessories",
    typ: "Empty",
    subTyp_1: "Empty",
    subTyp_2: "Empty",
  },
  {
    id: 6,
    dept: "Cleaning",
    url: "cleaning",
    typ: "Empty",
    subTyp_1: "Empty",
    subTyp_2: "Empty",
  },
  {
    id: 7,
    dept: "Security",
    url: "security",
    typ: "Empty",
    subTyp_1: "Empty",
    subTyp_2: "Empty",
  },
  {
    id: 8,
    dept: "Optics",
    url: "optics",
    typ: "Empty",
    subTyp_1: "Empty",
    subTyp_2: "Empty",
  },
  {
    id: 9,
    dept: "Hunting",
    url: "hunting",
    typ: "Empty",
    subTyp_1: "Empty",
    subTyp_2: "Empty",
  },
  {
    id: 10,
    dept: "Air Guns",
    url: "air-guns",
    typ: "Empty",
    subTyp_1: "Empty",
    subTyp_2: "Empty",
  },
];

export const allProducts = [
  {
    style_id: 1,
    name: "Salomon X Ultra 3 Mid GTX Hiking Boots - Men's",
    url: "Salomon-X-Ultra-3-Mid-GTX-Hiking-Boots-Mens",
    description:
      "Wet conditions, tough descents and long hikes are no problem for the men's Salomon X Ultra 3 Mid GTX hiking boots.",
    regular_price: 200,
    sales_price: "",
    gener: "variable",
    stock: 0,
    size: "",
    color: [],
    smallImage: "1-small.jpg",
    largeImage: "1-large.jpg",
    altImages: ["1-alt-olive-1.jpg", "1-alt-olive-2.jpg", "1-alt-olive-3.jpg"],
    dept: "firearms",
    typ: "firearms-guns",
    subTyp_1: "Empty",
    subTyp_2: "Empty",
    brand: "Nike",
    thumbnail: "",
    entryDate: "01-01-2021",
    featured: "yes",
    variants: [
      {
        size: "S",

        color: [
          {
            name: "olive",
            colorCode: "#bab86c",
            colorSmallImage: "1-small-olive.jpg",
            colorLargeImage: "1-large-olive.jpg",
            alt_images: [
              "1-alt-olive-1.jpg",
              "1-alt-olive-2.jpg",
              "1-alt-olive-3.jpg",
            ],
            stock: 10,
          },
          {
            name: "black",
            colorCode: "#008000",
            colorSmallImage: "",
            colorLargeImage: "1-large-black.jpg",
            alt_images: [
              "1-alt-black-1.jpg",
              "1-alt-black-2.jpg",
              "1-alt-black-3.jpg",
            ],
            stock: 0,
          },
        ],
        regular_price: 180,
        sales_price: 170,
      },
      {
        size: "M",

        color: [
          {
            name: "black",
            colorCode: "#000000",
            colorSmallImage: "1-small-black.jpg",
            colorLargeImage: "1-large-black.jpg",
            alt_images: [
              "1-alt-black-1.jpg",
              "1-alt-black-2.jpg",
              "1-alt-black-3.jpg",
            ],
            stock: 0,
          },
          {
            name: "navy",
            colorCode: "#003366",
            colorSmallImage: "1-small-navy.jpg",
            colorLargeImage: "1-large-navy.jpg",
            alt_images: [
              "1-alt-navy-1.jpg",
              "1-alt-navy-2.jpg",
              "1-alt-navy-3.jpg",
            ],
            stock: 4,
          },
        ],
        regular_price: 200,
        sales_price: "",
      },
    ],
  },
  {
    style_id: 2,
    name: "Fjallraven Keb Padded Insulated Hoodie - Men's",
    description:
      "Lightweight and versatile, the men's Fjallraven Keb Padded insulated hoodie is ideal for cold-weather exploring.",
    url: "fjallraven-keb-padded-insulated-hoodie-mens",
    regular_price: 40,
    sale_price: 38,
    gener: "simple",
    stock: 5,
    size: "",
    color: "",
    smallImage: "2-small.jpeg",
    largeImage: "2-large.jpeg",
    altImages: ["2-large.jpeg"],
    dept: "firearms",
    typ: "firearms-guns",
    subTyp_1: "Empty",
    subTyp_2: "Empty",
    brand: "polo",
    entryDate: "01-01-2020",
    featured: "no",
  },
  {
    style_id: 3,
    name: "KUHL Law Fleece-Lined Hoodie - Men's",
    description: "KUHL Law Fleece-Lined Hoodie - Men's",
    url: "kuhl-law-fleece-lined-hoodie-mens",
    regular_price: 120,
    sale_price: 117,
    gener: "simple",
    stock: 5,
    size: "",
    color: "",
    smallImage: "3-small.jpeg",
    largeImage: "3-large.jpeg",
    altImages: ["3-large.jpeg"],
    dept: "firearms",
    typ: "firearms-guns",
    subTyp_1: "firearms-guns-pistal",
    subTyp_2: "Empty",
    brand: "polo",
    entryDate: "01-01-2019",
    featured: "yes",
  },
  {
    style_id: 4,
    name: "Teva Tirra Sandals - Women's",
    description: "Teva Tirra Sandals - Women's",
    url: "teva-tirra-sandals-womens",
    regular_price: 20,
    sale_price: 17,
    gener: "simple",
    stock: 5,
    size: "",
    color: "",
    smallImage: "4-small.jpeg",
    largeImage: "4-large.jpeg",
    altImages: ["4-large.jpeg"],
    dept: "firearms",
    typ: "firearms-riffle",
    subTyp_1: "Empty",
    subTyp_2: "Empty",
    brand: "polo",
    entryDate: "01-02-2019",
    featured: "no",
  },
  {
    style_id: 5,
    name: "prAna Polar Escape Jacket - Women's",
    description: "prAna Polar Escape Jacket - Women's",
    url: "prana-polar-escape-jacket-womens",
    regular_price: 500,
    sale_price: 450,
    gener: "simple",
    stock: 5,
    size: "",
    color: "",
    smallImage: "5-small.jpeg",
    largeImage: "5-large.jpeg",
    altImages: ["5-large.jpeg"],
    dept: "Firearms",
    typ: "firearms-riffle",
    subTyp_1: "firearms-riffle-ak47",
    subTyp_2: "Empty",
    brand: "polo",
    featured: "yes",
  },

  {
    style_id: 6,
    name: "Smartwool Merino 250 Base Layer Crew - Kids' ",
    description: "Smartwool Merino 250 Base Layer Crew - Kids'",
    url: "smartwool-merino-250-base-layer-crew-kids",
    regular_price: 10,
    sale_price: 9,
    gener: "simple",
    stock: 0,
    size: "",
    color: "",
    smallImage: "6-small.jpeg",
    largeImage: "6-large.jpeg",
    altImages: ["6-large.jpeg"],
    dept: "firearms",
    typ: "Empty",
    subTyp_1: "Empty",
    subTyp_2: "Empty",
    brand: "polo",
    entryDate: "01-03-2021",
    featured: "no",
  },
];
